name: Dependabot
on: pull_request

permissions:
    contents: write
    pull-requests: write

jobs:
    auto-approve:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'
            - name: Approve a PR
              run: gh pr review --approve "$PR_URL"
              env:
                  PR_URL: '${{ github.event.pull_request.html_url }}'
                  GITHUB_TOKEN: '${{ secrets.GH_ACCESS_TOKEN }}'
    auto-merge:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'
        steps:
          - name: automerge
            uses: actions/github-script@v7.0.1
            with:
              script: |
                github.pullRequests.createReview({
                  owner: context.payload.repository.owner.login,
                  repo: context.payload.repository.name,
                  pull_number: context.payload.pull_request.number,
                  event: 'APPROVE'
                })
                github.pullRequests.merge({
                  owner: context.payload.repository.owner.login,
                  repo: context.payload.repository.name,
                  pull_number: context.payload.pull_request.number
                })
              github-token: ${{github.token}}
