name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  npmjs:
    runs-on: ubuntu-latest
    steps:
      - name: Set NPM_TOKEN
        run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.BOT_GITHUB_ACTIONS_2 }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_ACTIONS_2 }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #- run: npm run build:publish
      # env:
      # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: echo NPM_TOKEN
        run: echo $NPM_TOKEN
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_ACTIONS_2 }}
