name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      #- run: npm run build:publish
      # env:
      # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}